allure:
  report:
    name: "Java-Sele-TestScripts Automation Report"
    path: "allure-report"
  results:
    path: "allure-results"
  environment:
    - name: "OS"
      value: "Windows 11"
    - name: "Browser"
      value: "Chrome"
    - name: "Java"
      value: "21"
    - name: "TestNG"
      value: "7.x"
  categories:
    - name: "Skipped tests"
      matchedStatuses: [skipped]
    - name: "Failed tests"
      matchedStatuses: [failed]
    - name: "Broken tests"
      matchedStatuses: [broken]